BINARY=pg_trace
OBJECTS=main.o strace.o strdelim.o
OBJECTS+=${EXTRA_OBJECTS}

all: ${BINARY}

${BINARY}: ${OBJECTS}
	${CC} ${LDFLAGS} -o ${BINARY} ${OBJECTS} ${CURSESLIB} 

install: ${BINARY}
	install -d -m 755 ${PREFIX}/bin
	install -m 755 ${BINARY} ${PREFIX}/bin
	install -d -m 755 ${PREFIX}/${MANDEST}/man1
	install -m 644 ${BINARY}.1 ${PREFIX}/${MANDEST}/man1

mantest:
	nroff -man pg_trace.1 | less -R

clean:
	rm -f ${BINARY} ${OBJECTS} test.o run_tests *core


