BINARY=pg_trace

all:
	make -C src/

install: ${BINARY}
	install -d -m 755 ${PREFIX}/bin
	install -m 755 src/${BINARY} ${PREFIX}/bin
	install -d -m 755 ${PREFIX}/${MANDEST}/man1
	install -m 644 ${BINARY}.1 ${PREFIX}/${MANDEST}/man1

mantest:
	nroff -man pg_trace.1 | less -R

clean:
	make -C src/ clean

README: pg_trace.1
	nroff -man pg_trace.1 | col -b > README
